spring:
  application:
    name: spring-boot-mongo-graphql
  servlet:
    multipart:
      enabled: true
      location: /tmp
  data:
      mongodb:
         uri: mongodb://localhost:27017/blog
logging:
  level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
      com.mongdb: DEBUG
server:
  port: 9000
graphql:
  servlet:
      mapping: /graphql
      enabled: true
      corsEnabled: true
  tools:
      schemaLocationPattern: "**/*.graphqls"
